[package]
name = "anytaggy"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"

[dependencies]
thiserror = "2.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive", "string"] }
lets_find_up = "0.0.4"
sha2 = "0.10"
rusqlite = { version = "0.39", features = ["bundled"] }
rusqlite_migration = "2.5"
walkdir = "2.5"
derive_builder = "0.20.2"

[dev-dependencies]
rand = "0.10"
serial_test = "3.4.0"
temp-dir = "0.2.0"
