CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path VARCHAR(2000) NOT NULL,
    name VARCHAR(2000) NOT NULL,
    hash_sum TEXT UNIQUE NOT NULL
);

CREATE TABLE tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(2000) UNIQUE NOT NULL
);

CREATE TABLE file_tags (
    file_id INTEGER REFERENCES files (id),
    tag_id INTEGER REFERENCES tags (id)
);
