CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path VARCHAR(2000) NOT NULL,
    name VARCHAR(2000) NOT NULL,
    contents_hash TEXT UNIQUE NOT NULL,
    fingerprint_hash TEXT UNIQUE NOT NULL
);

CREATE TABLE tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(2000) UNIQUE NOT NULL
);

CREATE TABLE file_tags (
    file_id INTEGER REFERENCES files (id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES tags (id) ON DELETE CASCADE,
    UNIQUE (file_id, tag_id)
);
