name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare deps
      run: |
        cargo install cargo-nextest --locked
        cargo +stable install cargo-llvm-cov --locked
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo llvm-cov nextest
